name: whatsapp_field
description: "A customizable WhatsApp-style text form field for Flutter."
version: 1.0.0+1
#publish_to: https://pub.dev

repository: https://github.com/MeetMevadaStar/whatsapp_text_form_field
homepage: https://github.com/MeetMevadaStar/whatsapp_text_form_field

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  emoji_picker_flutter: ^2.2.0
  whatsapp_camera: ^1.0.0
  file_picker: ^5.5.0
  contacts_service: ^0.6.3
  permission_handler: ^10.4.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
